### ISSUE TITLE
Local and demo database does not open,  do not create a new database.

### ISSUE THREAD

**Issue by xAnder1402** [viossat/docker-keeweb-webdav#3]
Network Console:
Uncaught KdbxError {name: "KdbxError", code: "NotImplemented", message: "Error NotImplemented: Random not implemented"}code: "NotImplemented"message: "Error NotImplemented: Random not implemented"name: "KdbxError"__proto__: Object
random @ (index):2
getBytes @ (index):2
a.fromString @ (index):2
openDemo @ (index):17
(anonymous) @ (index):19
createDemoFile @ (index):19
createDemo @ (index):24
dispatch @ (index):11
q.handle @ (index):11

**Comment by viossat** [comment]
This issue doesn't look related to the WebDAV feature of this repo's Docker image. You should post it in the [original repo](https://github.com/keeweb/keeweb). As I have never met this issue, don't forget to include your browser/version.
