### ISSUE TITLE
使用nginx TLS反向代理webdav的陷阱(修复方案)

### ISSUE THREAD

**Issue by arschlochnop** [viossat/docker-keeweb-webdav#4]
**no TLS support, reverse proxy with TLS recommended 直接配置会有BUG**

使用默认的反向代理,在同步keeweb.kdbx时会使用move方法,但是move请求会出现502 bad gateway错误

研究后发现,request header里Destination 必须为反向代理的地址
在nginx.conf内加入
proxy_set_header Destination "http://proxy site:65330/webdav/keeweb.kdbx";

**nginx 反向代理配置**
```upstream google {
 server proxy site:65530 max_fails=3; 
 }
server {
        listen      443;
        server_name  your domain;
        ssl on;
        ssl_certificate /etc/1.pem;
        ssl_certificate_key /etc/privkey.pem;
location / {
                proxy_pass              http://proxy site:65330;
                proxy_set_header Destination "http://proxy site:65330/webdav/keeweb.kdbx";

}
} 
```

**Comment by viossat** [comment]
keeweb behind TLS reverse-proxy works great here without the need of an extra header.
